oxm_fields: make a crash less cryptic
when oxm length is not what we expect, explicitly raise an exception
with descriptive message like the following.

    Exception: Unexpected OXM payload length 3 for ipv6_flabel (expected 4)

This often happens if you are using LINC and IPv6.
https://github.com/FlowForwarding/of_protocol/pull/57