services/vrrp/event: introduce VRRP related events and classes
They are exported events and classes.

Cc: Hiroshi Yokoi <yokoi.hiroshi@po.ntts.co.jp>
Cc: yuta-hamada <yuta.hamada.z02@gimal.com>
Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>
---
Changes v4 -> v5:
- add state attribute to VRRPInstance
-  ryu/services/vrrp/event.py", in __init__
   super(EventVRRPListReply, self).__init__() TypeError:
   __init__() takes exactly 2 arguments (1 given)

Changes v2 -> v3:
- make StateChanged event include related all configs
  this is useful for sample_manager/router
- drop register request

Changes v1 -> v2:
- Linux network device support
- dynamic configuration change

fixed argument for event.EventReplyBase constructor.
ryu/services/vrrp/event.py", in __init__
    super(EventVRRPListReply, self).__init__()
TypeError: __init__() takes exactly 2 arguments (1 given)