fix a copy and paste mistake in "code simplification" change
run_tests.sh complained on the following change.

	commit 3f724f1929ef726db5361cb4cc4e3ac0e1b4bd19
	Author: Isaku Yamahata <yamahata@valinux.co.jp>
	Date:   Thu Nov 22 17:09:08 2012 +0900

	    ofproto_v1_2_parser: code simplification

======================================================================
ERROR: Failure: TypeError (__init__() takes exactly 3 arguments (1 given))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/eos-fs.nfskuro/git/ryu/.venv/lib/python2.6/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/nfs/eos-fs.nfskuro/git/ryu/.venv/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/nfs/eos-fs.nfskuro/git/ryu/.venv/lib/python2.6/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/nfs/eos-fs.nfskuro/git/ryu/ryu/tests/unit/ofproto/test_parser_v12.py", line 3062, in <module>
    class TestOFPQueuePropMinRate(unittest.TestCase):
  File "/nfs/eos-fs.nfskuro/git/ryu/ryu/tests/unit/ofproto/test_parser_v12.py",
line 3068, in TestOFPQueuePropMinRate
    c = OFPQueuePropMinRate(rate)
  File "/nfs/eos-fs.nfskuro/git/ryu/ryu/ofproto/ofproto_v1_2_parser.py", line 12
98, in __init__    super(OFPQueuePropMinRate, self).__init__()
  File "/nfs/eos-fs.nfskuro/git/ryu/ryu/ofproto/ofproto_v1_2_parser.py", line 12
60, in __init__
    cls.cls_len)
  File "/nfs/eos-fs.nfskuro/git/ryu/ryu/ofproto/ofproto_v1_2_parser.py", line 1236, in __init__
    super(OFPQueueProp, self).__init__()
TypeError: __init__() takes exactly 3 arguments (1 given)

----------------------------------------------------------------------

Signed-off-by: YAMAMOTO Takashi <yamamoto@valinux.co.jp>