services/vrrp/manager: introduce a class that manages VRRP routers
Cc: yuta-hamada <yuta.hamada.z02@gimal.com>
Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>
---
Changes v4 -> v5:
- manager.py: list_request_handler TypeError
  TypeError: __init__() takes exactly 5 arguments (4 given)
- appmanager.uninstantiate argument change
- add state to VRRPInstance

Changes v3 -> v4:
- eventlet

Changes v2 -> v3:
- comment
- typo
- drop register request handler

Changes v1 -> v2:
- dynamic configuration change
- trivial update for depending patch change