services/vrrp/router: VRRP router
Introduce VRRP router class which handles VRRP.

Cc: Hiroshi Yokoi <yokoi.hiroshi@po.ntts.co.jp>
Cc: yuta-hamada <yuta.hamada.z02@gimal.com>
Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>
---
Changes v4 -> v5:
- router.py: vrrp_config_change_request AttributeError
  AttributeError: 'VRRPRouterV3' object has no attribute 'address_owner'
- self.state_impl.vrrp_config_chnage_request(ev)
  AttributeError: 'VRRPV3StateMaster' object has no
  attribute 'vrrp_config_chnage_request'

Changes v3 -> v4:
- eventlet

Changes v2 -> v3:
- comment

Changes v1 -> v2:
- dynamic configuration change
- wrong priority comparison

fixed method name.
ryu/services/vrrp/router.py",  in vrrp_config_change_request_handler
    self.state_impl.vrrp_config_chnage_request(ev)
AttributeError: 'VRRPV3StateMaster' object has no attribute 'vrrp_config_chnage_request'

fixed attribute name.
ev.Advertisement_inerval to ev.advertisement_interval